name: Create and Release App
on:
  push:
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'
jobs:
  create_and_release_app:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1.7'
        arch: [x64, x86]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: macos-latest
            arch: x86
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@v1
        with:
          show-versioninfo: true
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
        with:
          project: compiler
      - name: Compile App
        run: julia --project=compiler -e 'include(joinpath("compiler", "runcompiler.jl")); compile_app()'
      - name: Test App
        run: julia --project=compiler -e 'include(joinpath("compiler", "runcompiler.jl")); test_app()'
      - name: Upload Binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: compiler/JuliaFormatter-*
